### PR TITLE
Laravel 11 support

### PR DESCRIPTION
**Pull request by Plytas**
Added Laravel 11 support as requested in #55. ~This also results in increased minimum php version to 8.2 as per Laravel documentation.~ We should be able to support php 8.1, but only for Laravel 10.
image

Most changes are from running `pint`.

Decided to drop Laravel 9 support as it's past it's end of life. Also updated CI to run test on php8.3 too.

### CODE REVIEW

**Comment by Plytas** [comment]
@gtmassey this requires a new version of https://github.com/gtmassey/period. I see there's a an open PR for it https://github.com/gtmassey/period/pull/2.

**Comment by gtmassey** [comment]
@Plytas I didn't see the original PR on Period, and now I'm messing around with the support. It looks like I will have to drop Laravel 9 support for Period as well, because I can't seem the package to support both L9 and L11 simultaneously, which is a bummer, because I'd like to keep the PHP base support to 8.1+ 

So, I'll work on adding laravel 11 support and dropping laravel 9 support on Period, which will also impact a few other things. Might take a bit for it to come through, then I'll re-run the tests here and approve the PR.

**Comment by gtmassey** [comment]
I'm not sure if this is possible with the different version constraints, but since Laravel 10 supports php8.1, I'm working to see if we can get this package and gtmassey/period to support php8.1 and up, while still supporting Laravel 10 and 11. But I think that it will cause conflicts with Laravel 11.

**Comment by gtmassey** [comment]
I updated a few things on composer, and ran pint, but the tests are failing for some reason. I haven't quite figured out why, but the error I keep getting is "Could not construct ApplicationDefaultCredentials" on several tests across the package.

**Review by gtmassey — APPROVED** [review]

**Pull request merged**
